[connections.snowflake]
url = "snowflake://jeneva.williams-blackwell@libertymutual.com@libertymutual_grm_us_edw.us-east-1"

[connections.snowflake.create_engine_kwargs.connect_args]
authenticator = "externalbrowser"
warehouse = "SAS_PROD_SELFSERVE_REPORTING_WH"
role = "USER_WILLIAMS_BLACKWELL_JENEVA_MASTER_ROLE"
client_session_keep_alive = true
